[unstable]
codegen-backend = true

[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

[profile.dev.package."*"]
opt-level = 3
codegen-backend = "llvm"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-Zshare-generics=y",
]

[alias]
r = [
  "run",
  "--release",
  "--features=bevy/dynamic_linking",
]
